export default {
  products: [
    {
      _id: '111111111111111111111111',
      name: 'Pikachu',
      category: 'Peluches Pikachu',
      image: './assets/bg-gray.jpg',
      price: 120,
      countInStock: 6,
      newSeason: true,
      discount: 0,
    },
    {
      _id: '2',
      name: 'Bulbasaur',
      category: 'Peluches',
      image: './assets/bg-gray.jpg',
      price: 100,
      countInStock: 9,
      newSeason: true,
      discount: 0,
    },
    {
      _id: '3',
      name: 'Mew',
      category: 'Llavero',
      image: './assets/bg-gray.jpg',
      price: 150,
      countInStock: 16,
      newSeason: true,
      discount: 0,
    },
    {
      _id: '4',
      name: 'Slowbro',
      category: 'Sitting Cutties',
      image: './assets/imgs/slowbro.jpg',
      price: 120,
      countInStock: 16,
      newSeason: false,
      discount: 10,
    },
    {
      _id: '5',
      name: 'Gengar',
      category: 'Sitting Cutties',
      image: './assets/imgs/gengar.jpg',
      price: 180,
      countInStock: 16,
      newSeason: false,
      discount: 50,
    },
    {
      _id: '6',
      name: 'Articuno',
      category: 'Sitting Cutties',
      image: './assets/imgs/articuno.jpg',
      price: 100,
      countInStock: 16,
      newSeason: false,
      discount: 15,
    },
  ],
};